### ISSUE TITLE
Add reduction in drop-down choices to the address fields of forms

### ISSUE THREAD

**Issue by TerryGarcia** [UTDallasEPICS/Kellermann-Foundation#18]
Allow for autocompletion of county, parishes, and villages or reduction in choices in their respective drop-down lists as user puts information into those fields

**Comment by nguyentridqu** [comment]
Fixed with commit https://github.com/UTDallasEPICS/Kellermann-Foundation/commit/4e815f0227f7da1951fb14c0efcb602a46eda8b1
